import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.time.DayOfWeek;
import java.time.LocalDateTime;
import java.time.Month;
import java.time.format.TextStyle;
import java.util.Locale;

/**
 * It represents a log where the application events are stored.
 * 
 * @author  Roberto Castillejo Embid
 * @version 1.0.
 */
public class Logger 
{
	private File file;		//The file where the events are saved.
	
	/**
	 * Constructor for Logger.
	 */
	public Logger()
	{
		file = new File("Multiply_Log.log");
	}
	
	/**
	 * Returns a File object.
	 * 
	 * @return	A File object.
	 */
	public File getFile()
	{
		return file;
	}
	
	/**
	 * Replace a File object with a new one passed as a parameter.
	 * 
	 * @param file		A File object.
	 */
	public void setArchivo(File file)
	{
		this.file = file;
	}
	
	/**
	 * Save the events generated by the application with the day, date and time they occur.
	 * 
	 * @param text		A file name.
	 */
	public void writeToLog(String text)
	{
		FileWriter out = null;
		PrintWriter pw = null;
		try{
			out = new FileWriter(file, true);
			pw = new PrintWriter(out);
			String date = insertDate(); //Saves the event date.
						
			if(file.length() == 0){		//The log is created
				pw.println("                                    APPLICATION LOG " + "\"" + "MULTIPLY" + "\"");
				pw.println();
				pw.println("                      ==============================================================");
				pw.println("                      * Author:      Roberto Castillejo Embid.                      *");
				pw.println("                      * Version:     1.0.                                           *");
				pw.println("                      ==============================================================");
				pw.println();
			}
			
			pw.print(date + "     ");
			pw.println(text);
		}
		catch(Exception e){
			System.out.println("Error: There was a problem with the log file: Multiply_Log.log");
		}
		finally{
			try{
			//Ensures the file is closed.
				if(out != null){
					out.close();
				}
			}
			catch(Exception e){
				System.out.println("Error: There was a problem closing the Multiply_Log.log file.");
			}
		}
	}
	
	
	/**
	 * Returns the current date in the specified format. An example of the format would be: 
	 * "Mon Dec 12 2016 22:17:43"
	 * 
	 * @return		The current date in a specific format.
	 */
	private String insertDate()
	{
		LocalDateTime dateNow = LocalDateTime.now();
		DayOfWeek dayOfWeek = dateNow.getDayOfWeek();
		Month monthOfYear = dateNow.getMonth();			
		String dayS = dayOfWeek.getDisplayName(TextStyle.SHORT, Locale.getDefault());
		String day = Integer.toString(dateNow.getDayOfMonth());
		String monthY = monthOfYear.getDisplayName(TextStyle.SHORT, Locale.getDefault());
		String anno = Integer.toString(dateNow.getYear());
		String hourStr;
		String minutesStr;
		String secondsStr;
		int seconds = dateNow.getSecond();
		int minutes = dateNow.getMinute();
		int hour = dateNow.getHour();
		
		//If the hours are less than 10, a 0 is added to the left of the value.
		if(hour < 10){
			hourStr = "0" + Integer.toString(hour);
		}
		else{
			hourStr = Integer.toString(hour);
		}
		
		//If the minutes are less than 10, a 0 is added to the left of the value..
		if(minutes < 10){
			minutesStr = "0" + Integer.toString(minutes);
		}
		else{
			minutesStr = Integer.toString(minutes);
		}
		
		//If the seconds are less than 10, a 0 is added to the left of the value.
		if(seconds < 10){
			secondsStr = "0" + Integer.toString(seconds);
		}
		else{
			secondsStr = Integer.toString(seconds);
		}
		
		return dayS + " " + monthY + " " + day + " " + anno + " " + hourStr + ":" + minutesStr + ":" + secondsStr;
	}
}
